---
title: "Instructions for Last Presentation"
---

\

\


### 1. Explaining your assigned R operator or command

\


Each researcher has been assigned a command in the participant list: https://docs.google.com/spreadsheets/d/1oROvpYepzb8evuDov1q8k5KE3BOJJt9s3BC4s3EGC2M/edit?gid=0#

\

Choose a command that says "fourth week".
You can choose a command that was presented by someone before you, in weeks 1-3, as long as you do not choose a command that you presented before.
Your presentation should include the following: 


- [ ] One slide defining the command. You can use technical language, but you should also use non-technical language, explaining it simply.
- [ ] One slide giving an example of how it's supposed to work (you can use an example from a code notebook) with a screenshot of you using the command. 
- [ ] One slide giving examples of mistakes that can occur with a screenshot of you demonstrating the mistake in your R console or terminal.

\

You should be prepared to spend no more than 5 minutes walking people through your command. Please put your slides in the google drive folder called "presentations describing commands". Here is an example set of slides: https://docs.google.com/presentation/d/1xz1qODz8Wkqf-2oLKKSTAYQBqrMNHK5k1lH32YZu5vo/edit#slide=id.g2f67101e387_0_17  

\

\

### 2. Final Presentation about the Mini-Project slides

\

As a second alternative you can use figures in Questions 1-3 in Part 1: Introduction to R and the R Syntax in Chapter 3: Data visualization to Correlate NB clinical variables with hypoxia phenotypes. Those figures can be found in the following link:

\

https://bioinformatics-bridge-course.netlify.app/exercises/exercises#part-1-introduction-to-r-and-the-r-syntax

\

\

### 3. Final Presentation about a Paper Figure

\

As a final alternative you can do your presentation about a figure in a paper of your choice or a paper that we discussed together.
